name = "Minecraft Modpack . Terr Firma Factions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
<<<<<<< Updated upstream
=======
hash = "5e37169aab7efb16ecb263ec11b7ce923439a063377457a519ff668559540727"
>>>>>>> Stashed changes

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
<<<<<<< Updated upstream

[options]
no-internal-hashes = true
=======
>>>>>>> Stashed changes
