// Reuse TFC's rock enum so fantasy ores need one block ID per quality.
const FantasyOreEnumProperty = Java.loadClass('net.minecraft.world.level.block.state.properties.EnumProperty')
const FantasyOreRockEnum = Java.loadClass('net.dries007.tfc.common.blocks.rock.Rock')
const FantasyOreRockValues = new (Java.loadClass('java.util.ArrayList'))()
FantasyOreRockEnum.values().forEach(rock => FantasyOreRockValues.add(rock))
// Select the Collection overload explicitly; Rhino also accepts lists as varargs.
const FantasyOreRockProperty = FantasyOreEnumProperty['create(java.lang.String,java.lang.Class,java.util.Collection)'](
    'rock', 'net.dries007.tfc.common.blocks.rock.Rock', FantasyOreRockValues
)
if (FantasyOreRockProperty.getPossibleValues().size() !== FantasyOreRockValues.size()) {
    throw new Error('Fantasy ore rock property did not include all TFC rocks')
}

StartupEvents.registry('block', event => {
    event.create('terra:alexandriite_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Copper Crystal')

    event.create('terra:byzantium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Cassiterite Crystal')

    event.create('terra:vitalum_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Sphalerite Crystal')

    event.create('terra:mugenium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Bismuthinite Crystal')

    event.create('terra:antinomia_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Silver Crystal')

    event.create('terra:vutironium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Gold Crystal')

    event.create('terra:durallium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Hematite Crystal')

    // Normal ore variants.
    event.create('terra:normal_alexandriite_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Alexandri’ite')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_byzantium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Byzantium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_vitalum_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Vitalum')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_mugenium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Mugenium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_antinomia_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Antinomia')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_vutironium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Vutironium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:normal_durallium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_iron_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Durallium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)


    // Crystalline ore supports crystal farming; regular and dense ores give normal and rich metal ore.
    event.create('terra:crystalline_alexandriite_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Alexandri’ite')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_byzantium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Byzantium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_vitalum_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Vitalum')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_mugenium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Mugenium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_antinomia_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Antinomia')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_vutironium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Vutironium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:crystalline_durallium_ore')
        .hardness(3.5)
        .tagBlock('minecraft:needs_iron_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Crystalline Durallium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)


    // Dense ore is the high-yield variant.
    event.create('terra:dense_alexandriite_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Alexandri’ite')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_byzantium_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Byzantium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_vitalum_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Vitalum')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_mugenium_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Mugenium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_antinomia_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Antinomia')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_vutironium_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_stone_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Vutironium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

    event.create('terra:dense_durallium_ore')
        .hardness(4.5)
        .tagBlock('minecraft:needs_iron_tool')
        .renderType('cutout')
        .property(FantasyOreRockProperty)
        .defaultState(state => state.set(FantasyOreRockProperty, 'tuff'))
        .displayName('Dense Durallium')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('c:ores')
        .requiresTool(true)

})
