#      `.                  `..      `..                  `.. ..                    
#     `. ..                 `..    `..                 `..    `..                  
#    `.  `..    `....        `.. `..`..   `..  `..      `..        `..      `..    
#   `..   `..  `..             `..`..  `..`..  `..        `..    `.   `.. `.   `.. 
#  `...... `..   `...          `.`..    `.`..  `..           `..`..... `.`..... `..
# `..       `..    `..         `..`..  `..`..  `..     `..    `.`.       `.        
#`..         `.`.. `..         `..  `..     `..`..       `.. ..   `....    `....   
#                                                                                  
#When enabled, allows filling foods with potion effects using the mod's mechanics.
isFoodFilling = true
#When enabled, items in the "create_food_filling:animals_food" tag are considered fillable, with higher priority than allow_filled.
isAnimalsFoodFilled = false
#The amount of fluid required to fill a food item with potion effects.
# Default: 250
# Range: 1 ~ 1000
foodFillingAmount = 250
#When enabled, eating foods with potion effects will apply those effects to the player.
isEatingApplyEffects = true
#Only active when 'isEatingApplyEffects' is enabled.
#UNABLE: Disable potion effect tooltips completely.
#CLIENT: Render tooltips on the client side.
#    Requires the mod to be installed on the client, otherwise tooltips will not be shown.
#SERVER: Bake tooltips into item Lore on the server.
#    Only requires the mod to be installed on the server.
#    (Note: Foods filled before enabling SERVER mode must be refilled to show tooltips.
#     Foods filled in SERVER mode will retain their tooltips even if switched to CLIENT mode later.)
#Allowed Values: UNABLE, CLIENT, SERVER
tooltipMode = "CLIENT"
