# Enable/Disable wire coating recipes in the crafting grid/packer/assembler.
# If disabled, wire coating recipes will only be accessible via the spout & wire coating factory.
enableGTWireCoatingRecipes: true

# Enable/Disable harder recipes for various Create blocks & items.
enableHardCreateRecipes: false

# Multiplier used for calculating fan processing time from rotational speed.
fanSpeedMultiplier: 0.75

# Should tiered encased fans process loose item entities?
processItemEntitiesWithFan: true

# Should Create items that have GTMR counterparts remain usable in Greate recipes?
# Requires a restart.
useCreateItemsInRecipes: true

# Should common Create recipes that conflict with GTMR progression be disabled?
disableConflictingRecipes: false

# Should recipes requested for removal but not found be logged?
logUnremovableRecipes: true

# Recipe types that should not be copied to Greate machines. Ex. 'gtceu:macerator' for macerator recipes
ignoredRecipeTypes:

# Mod IDs whose recipes should not be copied to Greate machines.
ignoredModIds:

